version: "3.2"

services:
  jenkins:
    container_name: jenkins-teste
    image: jenkins/jenkins:lts
    hostname: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - 80:8080
      - 50000:50000
    networks:
      - jenkins-teste-network

networks:
  jenkins-teste-network:
    driver: bridge
